- npm/src/cjson.ts
- npm/src/utils/file.ts
- npm/src/utils/is.ts
- npm/src/utils/json.ts
> updated jsdocs

- npm/package.json
- npm/src/cjson.ts
- tests/npm/package.json
- tests/npm/spec/tests/codedJsonTests.js
> closes #16, #21

- npm/package.json
- npm/src/cjson.ts
- npm/src/utils/is.ts
- npm/src/utils/json.ts
- npm/src/utils/keywords.ts
- python/cjson/src/cjson.py
- tests/npm/package.json
- tests/npm/spec/tests/codedJsonTests.js
- tests/test-files/relativeCalls.json
- tests/test-files/targetRelativeCalls.cjson
> Relative variable call

- npm/src/cjson.ts
- tests/test-files/callFromTarget.cjson
> closes #28 #30

- tests/.gitignore
- tests/python/cjson_tests.py
> tests completed

- README.md
- python/README.md
- tests/python/cjson_tests.py
> closes #34

- java/Coded-Json/pom.xml
- npm/README.md
- npm/package.json
> closes #11

- README.md
- java/Coded-Json/README.md
- java/Coded-Json/src/main/java/com/codedjson/CJson.java
- npm/README.md
- python/README.md
> closes #13

- .github/workflows/tests.yml
- java/Coded-Json/pom.xml
- java/Coded-Json/src/main/java/com/codedjson/Json.java
- java/Coded-Json/src/main/java/com/codedjson/exceptions/IllegalValueType.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Base.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/test/com/codedjson/Base.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
- java/Coded-Json/src/test/com/codedjson/JsonTests.java
- java/Coded-Json/src/test/com/codedjson/templates/CallFromTarget.java
- java/Coded-Json/src/test/com/codedjson/templates/Pure.java
- java/Coded-Json/src/test/com/codedjson/templates/Questions.java
- java/Coded-Json/src/test/com/codedjson/templates/RelativeCalls.java
- java/Coded-Json/src/test/com/codedjson/templates/Target.java
- java/Coded-Json/src/test/com/codedjson/templates/TargetObj.java
- java/Coded-Json/src/test/com/codedjson/templates/TargetRelativeCalls.java
- tests/test-files/source.json
> Java unit tests and pipeline

- npm/package.json
- npm/src/cjson.ts
- npm/src/utils/errors.ts
- npm/src/utils/keywords.ts
- npm/src/utils/refinery.ts
- tests/npm/package.json
- tests/npm/spec/tests/codedJsonTests.js
> closes #44

- .github/workflows/java-tests.yml
- .github/workflows/npm-tests.yml
- .github/workflows/python-tests.yml
- README.md
- npm/README.md
- python/README.md
- tests/python/cjson_tests.py
> Updated readme for v1.3.2

- README.md
- java/Coded-Json/README.md
> closes #24

- dotnet/.gitignore
- dotnet/Coded-Json/Coded-Json.sln
- dotnet/Coded-Json/Coded-Json/CJson.cs
- dotnet/Coded-Json/Coded-Json/Coded-Json.csproj
- dotnet/Coded-Json/Coded-Json/Support/Base.cs
- dotnet/Coded-Json/Coded-Json/Support/Decode.cs
- dotnet/Coded-Json/Coded-Json/Support/Int.cs
- dotnet/Coded-Json/Coded-Json/Support/Is.cs
> pulled dotnet code

- java/Coded-Json/src/main/java/com/codedjson/CJson.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Base.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
> closes #64

- README.md
- dotnet/CJson/README.md
> closes #83

- .gitignore
- document_generator.bat
- dotnet/CJson/CJson/CJson.csproj
- java/Coded-Json/pom.xml
closes #86 
C# docs are pushed manually at this stage
> closes #86

- npm/src/cjson.ts
- npm/src/utils/json.ts
- python/cjson/src/cjson.py
- python/cjson/src/utils/_base.py
- python/cjson/src/utils/_exceptions.py
- python/cjson/src/utils/_is.py
- python/cjson/src/utils/_json.py
- python/cjson/src/utils/file.py
- python/cjson/src/utils/keywords.py
- python/setup.py
- tests/python/cjson_tests.py
> closes #109 #115

- document_generator.bat
- dotnet/.gitignore
- dotnet/CJson/CJson/.gitignore
- dotnet/CJson/CJsonTests/Tests.cs
- dotnet/CJson/CJsonTests/models/CJsonContentTarget.cs
- dotnet/CJson/CJsonTests/models/Source.cs
- dotnet/CJson/README.md
- dotnet/CJson/docfx.json
- dotnet/CJson/index.md
- dotnet/CJson/toc.yml
> closes #97

- document_generator.bat
- dotnet/.gitignore
- dotnet/CJson/CJson/.gitignore
- dotnet/CJson/CJsonTests/Tests.cs
- dotnet/CJson/CJsonTests/models/CJsonContentTarget.cs
- dotnet/CJson/CJsonTests/models/Source.cs
- dotnet/CJson/README.md
- dotnet/CJson/docfx.json
- dotnet/CJson/index.md
- dotnet/CJson/toc.yml
- java/Coded-Json/pom.xml
- java/Coded-Json/src/main/java/com/codedjson/Main.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Base.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/test/com/codedjson/CJsonToStringTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonRemoveTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
- java/Coded-Json/src/test/com/codedjson/JsonTests.java
- java/Coded-Json/src/test/com/codedjson/templates/RawTarget.java
- java/Coded-Json/src/test/com/codedjson/templates/Source.java
> closes #123

- README.md
- docs/index.html
- java/Coded-Json/pom.xml
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
> closes #107 #127

- README.md
- docs/index.html
- java/Coded-Json/pom.xml
- java/Coded-Json/src/main/java/com/codedjson/Json.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
> closes #130

- java/Coded-Json/src/main/java/com/codedjson/CJson.java
- java/Coded-Json/src/main/java/com/codedjson/Json.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Base.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Keywords.java
- java/Coded-Json/src/test/com/codedjson/Base.java
- java/Coded-Json/src/test/com/codedjson/CJsonToStringTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonRemoveTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
- java/Coded-Json/src/test/com/codedjson/JsonTests.java
- java/Coded-Json/src/test/com/codedjson/templates/ReferInjectedVariable.java
- java/Coded-Json/src/test/com/codedjson/templates/TargetObj.java
- java/Coded-Json/src/test/com/codedjson/templates/TargetRelativeCalls.java
- java/Coded-Json/src/test/com/codedjson/templates/VariableInjection.java
> closes #132

- java/Coded-Json/src/test/com/codedjson/Base.java
- java/Coded-Json/src/test/com/codedjson/JsonTests.java
- tests/test-files/invalid.json
Code coverage for current main branch 
Code coverage for issue-110 branch
> Issue 110-Code Coverage for Java

- dotnet/CJson/CJson/Utils/Decode.cs
- dotnet/CJson/CJsonTests/Tests.cs
- java/Coded-Json/src/test/com/codedjson/CJsonToStringTests.java
> closes #138

- dotnet/CJson/CJson/CJson.cs
- dotnet/CJson/CJson/Exceptions/VariableInjectionException.cs
- dotnet/CJson/CJson/Utils/Decode.cs
- dotnet/CJson/CJson/Utils/Keywords.cs
- dotnet/CJson/CJsonTests/Tests.cs
- dotnet/CJson/CJsonTests/models/TargetObj.cs
> closes #135

- .gitignore
- cjson/src/auto_completes/completion-items.ts
- cjson/src/auto_completes/register.ts
- cjson/src/utils/interfaces.ts
- cjson/src/utils/utils.ts
- cjson/syntaxes/cjson.tmLanguage.json
> Issue 155 159

- cjson/syntaxes/cjson.tmLanguage.json
> closes #161

- java/Coded-Json/src/main/java/com/codedjson/CJson.java
- java/Coded-Json/src/main/java/com/codedjson/Main.java
- java/Coded-Json/src/main/java/com/codedjson/exceptions/UnsupportedDatatypeForImport.java
- java/Coded-Json/src/main/java/com/codedjson/types/Constants.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Decode.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Is.java
- java/Coded-Json/src/main/java/com/codedjson/utils/Keywords.java
- java/Coded-Json/src/test/com/codedjson/CJsonToStringTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonRemoveTests.java
- java/Coded-Json/src/test/com/codedjson/CjsonTests.java
- java/Coded-Json/src/test/com/codedjson/JsonTests.java
- tests/test-files/asKeywordTest.cjson
> Closes #180
